Repository monsieurbiz/SyliusSettingsPlugin, pull requests merged in 2023-01, with the labels that each got.

#52 add support to bypass prepending migrations
  src/DependencyInjection/MonsieurBizSyliusSettingsExtension.php
Labels: quick win

#54 ci: Fix PHP setup
  .github/workflows/recipe.yaml
  .github/workflows/security.yaml
  .github/workflows/tests.yaml
Labels: Status: needs review

#55 feat: Sylius 1.12 compatibility
  .github/workflows/recipe.yaml
  .github/workflows/security.yaml
  .github/workflows/tests.yaml
  .gitignore
  .php-cs-fixer.dist.php
  .php-version.dist
  Makefile
  composer.json
  phpstan.neon
  phpunit.xml.dist
  src/Controller/SettingsController.php
  src/DependencyInjection/InstantiateSettingsPass.php
  src/DependencyInjection/MonsieurBizSyliusSettingsExtension.php
  src/Entity/Setting/Setting.php
  src/Factory/SettingFactory.php
  src/Form/AbstractSettingsType.php
  src/Form/MainSettingsType.php
  src/Processor/SettingsProcessor.php
  src/Repository/SettingRepository.php
  src/Settings/Metadata.php
  src/Settings/MetadataInterface.php
  src/Settings/Settings.php
  src/Settings/SettingsInterface.php
  symfony.lock
  tests/Unit/.gitkeep
Labels: Status: needs review

#56 fix: getParameter method should return mixed
  src/Settings/Metadata.php
  src/Settings/MetadataInterface.php
  src/Settings/Settings.php
Labels: Priority: high, Status: needs review
